# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    # copied from `tools/linux_ci_setup.sh`
    - automake
    - build-essential
    - libtool
    - make
    - cmake
    - libgslcblas0
    - libgsl-dev
    - libeigen3-dev
    - libnlopt-dev
    - libnlopt-cxx-dev
  jobs:
    pre_install:
      # copied from `tools/linux_ci_env.sh`
      - ls /usr/lib/x86_64-linux-gnu/
      - export EIGEN_DIR="/usr/include/eigen3"
      - export NLOPT_DIR="/usr/lib/x86_64-linux-gnu/"
      - export CMAKE_C_COMPILER="/usr/bin/gcc-11"
      - export CMAKE_CXX_COMPILER="/usr/bin/g++-11"
      - export TEST_EXC="'/usr/include/*'"
      - env
sphinx:
  configuration: docs/source/conf.py
python:
  install:
  - method: pip
    path: .
    extra_requirements:
      - docs
