# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - automake
    - build-essential
    - libtool
    - make
    - cmake
    - libgslcblas0
    - libgsl-dev
    - libeigen3-dev
    - libnlopt-dev
    - libnlopt-cxx-dev
  jobs:
    pre_install:
      - source ./tools/linux_ci_env.sh
sphinx:
  configuration: docs/source/conf.py
python:
  install:
  - method: pip
    path: .
    extra_requirements:
      - docs
