

#ifndef CONTINUOUS_MODEL_DEFINE
#define CONTINUOUS_MODEL_DEFINE

typedef  int contbmd; 


#define CONTINUOUS_BMD_ABSOLUTE     1
#define CONTINUOUS_BMD_STD_DEV      2
#define CONTINUOUS_BMD_REL_DEV      3
#define CONTINUOUS_BMD_POINT        4
#define CONTINUOUS_BMD_EXTRA        5
#define CONTINUOUS_BMD_HYBRID_EXTRA 6
#define CONTINUOUS_BMD_HYBRID_ADDED 7
#define CONTINUOUS_BMD_EMPTY        0.0


#define PROFILE_INEQUALITY   1000
#define PROFILE_EQUALITY     2000

#endif
