from typing import ClassVar, List

d_gamma: dich_model
d_hill: dich_model
d_logistic: dich_model
d_loglogistic: dich_model
d_logprobit: dich_model
d_multistage: dich_model
d_probit: dich_model
d_qlinear: dich_model
d_weibull: dich_model
exp_3: cont_model
exp_5: cont_model
funl: cont_model
generic: cont_model
hill: cont_model
log_normal: distribution
nctr: nested_model
nlogistic: nested_model
normal: distribution
normal_ncv: distribution
polynomial: cont_model
power: cont_model

class BMDSMA_results:
    BMD: List[float]
    BMDL: List[float]
    BMDL_MA: float
    BMDU: List[float]
    BMDU_MA: float
    BMD_MA: float
    ebLower: List[float]
    ebUpper: List[float]
    def __init__(self) -> None: ...

class BMDS_results:
    AIC: float
    BIC_equiv: float
    BMD: float
    BMDL: float
    BMDU: float
    bounded: List[bool]
    chisq: float
    lowerConf: List[float]
    slopeFactor: float
    stdErr: List[float]
    upperConf: List[float]
    validResult: bool
    def __init__(self) -> None: ...
    def setSlopeFactor(self, arg0: float) -> None: ...

class cont_model:
    __members__: ClassVar[dict] = ...  # read-only
    __entries: ClassVar[dict] = ...
    exp_3: ClassVar[cont_model] = ...
    exp_5: ClassVar[cont_model] = ...
    funl: ClassVar[cont_model] = ...
    generic: ClassVar[cont_model] = ...
    hill: ClassVar[cont_model] = ...
    polynomial: ClassVar[cont_model] = ...
    power: ClassVar[cont_model] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __setstate__(self, state: int) -> None: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class continuous_AOD:
    AIC: List[float]
    LL: List[float]
    TOI: testsOfInterest
    addConst: float
    nParms: List[int]
    def __init__(self) -> None: ...

class continuous_GOF:
    calcMean: List[float]
    calcSD: List[float]
    dose: List[float]
    ebLower: List[float]
    ebUpper: List[float]
    estMean: List[float]
    estSD: List[float]
    n: int
    obsMean: List[float]
    obsSD: List[float]
    res: List[float]
    size: List[float]
    def __init__(self) -> None: ...

class dich_model:
    __members__: ClassVar[dict] = ...  # read-only
    __entries: ClassVar[dict] = ...
    d_gamma: ClassVar[dich_model] = ...
    d_hill: ClassVar[dich_model] = ...
    d_logistic: ClassVar[dich_model] = ...
    d_loglogistic: ClassVar[dich_model] = ...
    d_logprobit: ClassVar[dich_model] = ...
    d_multistage: ClassVar[dich_model] = ...
    d_probit: ClassVar[dich_model] = ...
    d_qlinear: ClassVar[dich_model] = ...
    d_weibull: ClassVar[dich_model] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __setstate__(self, state: int) -> None: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class dicho_AOD:
    devFit: float
    devRed: float
    dfFit: int
    dfRed: int
    fittedLL: float
    fullLL: float
    nFit: int
    nFull: int
    nRed: int
    pvFit: float
    pvRed: float
    redLL: float
    def __init__(self) -> None: ...

class dichotomous_GOF:
    df: float
    ebLower: List[float]
    ebUpper: List[float]
    expected: List[float]
    n: int
    p_value: float
    residual: List[float]
    test_statistic: float
    def __init__(self) -> None: ...

class distribution:
    __members__: ClassVar[dict] = ...  # read-only
    __entries: ClassVar[dict] = ...
    log_normal: ClassVar[distribution] = ...
    normal: ClassVar[distribution] = ...
    normal_ncv: ClassVar[distribution] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __setstate__(self, state: int) -> None: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class nestedBootstrap:
    numRuns: int
    pVal: List[float]
    perc50: List[float]
    perc90: List[float]
    perc95: List[float]
    perc99: List[float]
    def __init__(self) -> None: ...

class nestedLitterData:
    LSC: List[float]
    SR: List[float]
    dose: List[float]
    estProb: List[float]
    expected: List[float]
    litterSize: List[float]
    numRows: int
    observed: List[int]
    def __init__(self) -> None: ...

class nestedReducedData:
    dose: List[float]
    lowerConf: List[float]
    numRows: int
    propAffect: List[float]
    upperConf: List[float]
    def __init__(self) -> None: ...

class nested_model:
    __members__: ClassVar[dict] = ...  # read-only
    __entries: ClassVar[dict] = ...
    nctr: ClassVar[nested_model] = ...
    nlogistic: ClassVar[nested_model] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __setstate__(self, state: int) -> None: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class python_continuous_analysis:
    BMD_type: int
    BMR: float
    Y: List[float]
    alpha: float
    burnin: int
    degree: int
    detectAdvDir: bool
    disttype: int
    doses: List[float]
    isIncreasing: bool
    model: cont_model
    n: int
    n_group: List[float]
    parms: int
    prior: List[float]
    prior_cols: int
    restricted: bool
    samples: int
    sd: List[float]
    suff_stat: bool
    tail_prob: float
    transform_dose: int
    def __init__(self) -> None: ...

class python_continuous_model_result:
    aod: continuous_AOD
    bmd: float
    bmd_dist: List[float]
    bmdsRes: BMDS_results
    cov: List[float]
    dist: int
    dist_numE: int
    gof: continuous_GOF
    max: float
    model: int
    model_df: float
    nparms: int
    parms: List[float]
    total_df: float
    def __init__(self) -> None: ...

class python_dichotomousMA_analysis:
    actual_parms: List[int]
    modelPriors: List[float]
    models: List[int]
    nmodels: int
    nparms: List[int]
    prior_cols: List[int]
    priors: List[List[float]]
    pyDA: python_dichotomous_analysis
    def __init__(self) -> None: ...

class python_dichotomousMA_result:
    bmd_dist: List[float]
    bmdsRes: BMDSMA_results
    dist_numE: int
    models: List[python_dichotomous_model_result]
    nmodels: int
    post_probs: List[float]
    def __init__(self) -> None: ...

class python_dichotomous_analysis:
    BMD_type: int
    BMR: float
    Y: List[float]
    alpha: float
    burnin: int
    degree: int
    doses: List[float]
    model: int
    n: int
    n_group: List[float]
    parms: int
    prior: List[float]
    prior_cols: int
    samples: int
    def __init__(self) -> None: ...

class python_dichotomous_model_result:
    aod: dicho_AOD
    bmd: float
    bmd_dist: List[float]
    bmdsRes: BMDS_results
    cov: List[float]
    dist_numE: int
    gof: dichotomous_GOF
    gof_chi_sqr_statistic: float
    gof_p_value: float
    max: float
    model: int
    model_df: float
    nparms: int
    parms: List[float]
    total_df: float
    def __init__(self) -> None: ...

class python_multitumor_analysis:
    BMD_type: int
    BMR: float
    alpha: float
    degree: List[int]
    models: List[List[python_dichotomous_analysis]]
    n: List[int]
    ndatasets: int
    nmodels: List[int]
    prior_cols: int
    def __init__(self) -> None: ...

class python_multitumor_result:
    BMD: float
    BMDL: float
    BMDU: float
    combined_LL: float
    combined_LL_const: float
    models: List[List[python_dichotomous_model_result]]
    ndatasets: int
    nmodels: List[int]
    selectedModelIndex: List[int]
    slopeFactor: float
    validResult: List[bool]
    def __init__(self) -> None: ...
    def setSlopeFactor(self, arg0: float) -> None: ...

class python_nested_analysis:
    BMD_type: int
    BMR: float
    ILC_type: int
    LSC_type: int
    alpha: float
    background: float
    doses: List[float]
    incidence: List[float]
    iterations: int
    litterSize: List[float]
    lsc: List[float]
    model: int
    restricted: bool
    seed: int
    def __init__(self) -> None: ...

class python_nested_result:
    LL: float
    SRs: List[float]
    bmdsRes: BMDS_results
    boot: nestedBootstrap
    combPVal: float
    cov: List[float]
    df: float
    fixedLSC: float
    litter: nestedLitterData
    max: float
    model: nested_model
    nparms: int
    obsChiSq: float
    parms: List[float]
    reduced: nestedReducedData
    def __init__(self) -> None: ...

class test_struct:
    BMD: float
    doses: List[float]
    n: int
    validResult: bool
    def __init__(self) -> None: ...

class testsOfInterest:
    DF: List[float]
    llRatio: List[float]
    pVal: List[float]
    def __init__(self) -> None: ...

def add2(i: int, j: int) -> int: ...
def pythonBMDSCont(python_continuous_analysis: python_continuous_analysis, python_continuous_model_result: python_continuous_model_result) -> None: ...
def pythonBMDSDicho(python_dichotomous_analysis: python_dichotomous_analysis, python_dichotomous_model_result: python_dichotomous_model_result) -> None: ...
def pythonBMDSDichoMA(python_dichotomousMA_analysis: python_dichotomousMA_analysis, python_dichotomousMA_result: python_dichotomousMA_result) -> None: ...
def pythonBMDSMultitumor(python_multitumor_analysis: python_multitumor_analysis, python_multitumor_result: python_multitumor_result) -> None: ...
def pythonBMDSNested(python_nested_analysis: python_nested_analysis, python_nested_result: python_nested_result) -> None: ...
def version() -> str: ...
