name: Build python packages

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   tags:

jobs:

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-12]
    steps:
      - uses: actions/checkout@v4
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0
        env:
          CIBW_BUILD: "cp311-* cp312-* *-macosx_arm64 *-win_amd64 *-manylinux_x86_64"
      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
