name: Build Python Packages

on:
  schedule:
    - cron: '30 3 1 */1 *'  # At 03:30 on the 1st of every month
  push:
    tags:
      - '*'
  workflow_dispatch:
  pull_request:

env:
  CIBW_ARCHS: "auto64"
  CIBW_BUILD: "cp311-* cp312-* cp313-*"
  CIBW_SKIP: "*-win32 *-win_arm64 *musllinux* *i686 *-macosx_x86_64 *-macosx_universal2"
  CIBW_TEST_REQUIRES: "pytest pytest-mpl"
  CIBW_TEST_COMMAND: "pytest {project}/tests"

jobs:

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-14]
        CIBW_BEFORE_BUILD:
          ubuntu-22.04: "tools/cibuildwheel-linux.sh"
          windows-2022: "bash tools/windows_ci.sh"
          macos-14: "tools/cibuildwheel-mac.sh"
        EIGEN_DIR:
          ubuntu-22.04: "/usr/include/eigen3"
          windows-2022: "D:/a/bmds/bmds/deps/eigen"
          macos-14: "/opt/homebrew/Cellar/eigen/3.4.0_1/include/eigen3"
        NLOPT_DIR:
          ubuntu-22.04: "/usr/local/lib64/"
          windows-2022: "D:/a/bmds/bmds/deps/nlopt/src/api;D:/a/bmds/bmds/deps/nlopt/build/Release;D:/a/bmds/bmds/deps/nlopt/build"
          macos-14: "/opt/homebrew/Cellar/nlopt/2.7.1/include"
        GSL_DIR:
          windows-2022: "D:/a/bmds/bmds/deps/gsl/build/Release;D:/a/bmds/bmds/deps/gsl/build"
          macos-14: "/opt/homebrew/Cellar/gsl/2.7.1"
    steps:
      - uses: actions/checkout@v4
      - name: Build wheels
        uses: pypa/cibuildwheel@v3.1.3
        env:
          CIBW_BEFORE_BUILD: ${{ matrix.CIBW_BEFORE_BUILD[matrix.os] }}
          EIGEN_DIR: ${{ matrix.EIGEN_DIR[matrix.os] }}
          NLOPT_DIR: ${{ matrix.NLOPT_DIR[matrix.os] }}
          GSL_DIR: ${{ matrix.GSL_DIR[matrix.os] }}
          MACOSX_DEPLOYMENT_TARGET: "14.0"
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-linux-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  merge_wheels:
    runs-on: ubuntu-latest
    needs: build_wheels
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: wheels
          delete-merged: true
