name: Build Python Packages

on:
  schedule:
    - cron: '30 3 1 */1 *'  # At 03:30 on the 1st of every month
  push:
    tags:
      - '*'
  workflow_dispatch:
  pull_request:  # TODO - remove this line

env:
  CIBW_ARCHS: "auto64"
  CIBW_BUILD: "cp311-* cp312-* cp313-*"
  CIBW_SKIP: "*-win32 *-win_arm64 *musllinux* *i686 *-macosx_x86_64 *-macosx_universal2"
  CIBW_TEST_REQUIRES: "pytest pytest-mpl"
  CIBW_TEST_COMMAND: "pytest {project}/tests"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-22.04, windows-2022, macos-14]  # TODO - uncomment this line
        os: [ubuntu-22.04]  # TODO - remove this line
    steps:
      - uses: actions/checkout@v4

      - name: Set environment variables for Linux
        if: runner.os == 'Linux'
        shell: bash
        run: |
          echo "CIBW_BEFORE_BUILD=tools/cibuildwheel-linux.sh" >> $GITHUB_ENV
          echo "EIGEN_DIR=/usr/include/eigen3" >> $GITHUB_ENV
          echo "NLOPT_DIR=/usr/local/lib64/" >> $GITHUB_ENV

      - name: Set environment variables for Windows
        if: runner.os == 'Windows'
        shell: bash
        run: |
          echo "CIBW_BEFORE_BUILD=bash tools/windows_ci.sh" >> $GITHUB_ENV
          echo "EIGEN_DIR=D:/a/bmds/bmds/deps/eigen" >> $GITHUB_ENV
          echo "NLOPT_DIR=D:/a/bmds/bmds/deps/nlopt/src/api;D:/a/bmds/bmds/deps/nlopt/build/Release;D:/a/bmds/bmds/deps/nlopt/build" >> $GITHUB_ENV
          echo "GSL_DIR=D:/a/bmds/bmds/deps/gsl/build/Release;D:/a/bmds/bmds/deps/gsl/build" >> $GITHUB_ENV

      - name: Set environment variables for macOS
        if: runner.os == 'macOS'
        shell: bash
        run: |
          echo "CIBW_BEFORE_BUILD=tools/cibuildwheel-mac.sh" >> $GITHUB_ENV
          echo "EIGEN_DIR=/opt/homebrew/Cellar/eigen/3.4.0_1/include/eigen3" >> $GITHUB_ENV
          echo "NLOPT_DIR=/opt/homebrew/Cellar/nlopt/2.7.1/include" >> $GITHUB_ENV
          echo "GSL_DIR=/opt/homebrew/Cellar/gsl/2.7.1" >> $GITHUB_ENV
          echo "MACOSX_DEPLOYMENT_TARGET=14.0" >> $GITHUB_ENV

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.1.3
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-linux-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  merge_wheels:
    runs-on: ubuntu-latest
    needs: build_wheels
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: wheels
          delete-merged: true
