name: Build Python Packages

on:
  schedule:
    - cron: '30 3 1 */1 *'  # At 03:30 on the 1st of every month
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-14]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Show wheels that will be built
        run: |
          python -m pip install cibuildwheel==2.18.1
          cibuildwheel --print-build-identifiers
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.18.1
        env:
          MACOSX_DEPLOYMENT_TARGET: "14.0"
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  merge_wheels:
    runs-on: ubuntu-22.04
    needs: build_wheels
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: wheels
          delete-merged: true
